# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_semaphore
    cocoapods
  end

  desc "Build the app to verify it compiles"
  lane :build do
    match(type: "development")
    gym(scheme: 'TikTokTrainer',
        skip_package_ipa: true,
        skip_archive: true,
        clean: true)
  end

  lane :test do
    run_tests(scheme: "TikTokTrainer")
  end

  lane :lint_all do
    lint
    lint_tests
    lint_ui_tests
  end

  lane :lint do
    swiftlint(path: "TikTokTrainer", executable: "Pods/SwiftLint/swiftlint")
  end

  lane :lint_tests do
    swiftlint(path: "TikTokTrainerTests", executable: "Pods/SwiftLint/swiftlint")
  end

  lane :lint_ui_tests do
    swiftlint(path: "TikTokTrainerUITests", executable: "Pods/SwiftLint/swiftlint")
  end

  lane :beta do
    match(type: "appstore")
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "TikTokTrainer.xcodeproj"
    )
    gym(scheme: 'TikTokTrainer', export_method: "app-store")
    upload_to_testflight
  end
end
