# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_semaphore
  end

  desc "Build the app to verify it compiles"
  lane :build do
    match(type: "appstore")
    gym(scheme: 'TikTokTrainer',
        clean: true,
        export_method: "app-store")
  end

  lane :test do
    run_tests(scheme: "TikTokTrainer")
  end

  lane :beta do
    match(type: "appstore")
    gym(scheme: 'TikTokTrainer', export_method: "app-store")
    upload_to_testflight
  end
end
